[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "neojax-operators"
version = "0.0.2"
description = "Neural Operators in JAX"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
  { name = "Paul Gekeler", email = "pgekeler@gmail.com" },
]
keywords = [
  "jax",
  "neural-operators",
  "fno",
  "deep-learning",
  "scientific-computing",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
  "jax",
  "jaxlib",
  "equinox",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "ruff",
    "mypy",
    "torch>=2.0.0", # only devs/CI
    "neuraloperator"
]

[project.optional-dependencies]
docs = [
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings[python]",
]

[tool.hatch.build.targets.wheel]
packages = ["neojax"]

[project.urls]
Homepage = "https://github.com/paulgekeler/neojax"

# Ruff config
[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
# E/W = pycodestyle, F = Pyflakes (logic), I = isort (imports), UP = pyupgrade
select = ["E", "W", "F", "I", "UP", "B", "D"]
ignore = ["E501", "E741", "F722", "F821", "D107", "D417"]
extend-select = ["W505"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pycodestyle]
max-doc-length = 72

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

# mypy config
[tool.mypy]
python_version = "3.10"
strict = true
warn_return_any = true
warn_unused_configs = true
